version: '3'

services:
  client:
    image: hub.mingdao.com/beck/orleans/client-test:0.0.9
    volumes:
      - /usr/local/beck/docker/orleans/test/client:/app/Config
  silo:
    image: hub.mingdao.com/beck/orleans/silo-test:0.0.21
    volumes:
      - /usr/local/beck/docker/orleans/test/silo:/app/Config
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.labels.node_234 == 1


